services:
  app:
    image: automation-service:1.0.0
    container_name: automation-app
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - automation-network
    depends_on:
      - redis
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1.5G
        reservations:
          memory: 512M

  redis:
    image: redis:7-alpine
    container_name: redis-master
    command: ['redis-server', '--appendonly', 'yes']
    ports:
      - '6380:6379'
    volumes:
      - redis_data:/data
    networks:
      - automation-network
    restart: always

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - '5540:5540'
    volumes:
      - redisinsight_data:/data
    networks:
      - automation-network
    depends_on:
      - redis
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongodb-server
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secretpassword
    volumes:
      - mongo_data:/data/db
    networks:
      - automation-network
    restart: always

volumes:
  redis_data:
  redisinsight_data:
  mongo_data:

networks:
  automation-network:
